don't fail on first error by default
add -e option that brings this behaviour back.
now, by default, we fail with the last failed push's error code (if any) after
all pushes have completed.

diff --git a/git-multipush b/git-multipush
--- a/git-multipush
+++ b/git-multipush
@@ -6,12 +6,14 @@
 ## Particularly useful for people hosting on multiple git repo providers all
 ## at once. e.g., github.com, gitorious.org and repo.or.cz.
 ##
-## Usage: git multipush [-v] [-n] [-b <branch>] [<remote>...] [-- GIT_OPTIONS]
+## Usage: git multipush [-v] [-e] [-n] [-b <branch>] [<remote>...] [-- GIT_OPTIONS]
 ##
 ## <branch> is the branch to push -- if none given, pass none to git push
 ## <remote>... is the list of remotes to push to -- defaults to origin
 ##
 ## -v -- print each command as it is run.
+## -e -- fail immediately when any push fails. Otherwise, we fail after all
+##       pushes with the error code of the last failed push.
 ## -n -- don't run any commands, just print them.
 ## -b <branch> -- push <branch> instead of `git symbolic-ref HEAD`
 ## -d -- debug
@@ -37,7 +39,7 @@ set -u
 set -e
 
 usage() {
-    echo "Usage: git multipush [-v] [-n] [-b <branch>] [<remote>...] [-- GIT_OPTIONS]"
+    echo "Usage: git multipush [-v] [-e] [-n] [-b <branch>] [<remote>...] [-- GIT_OPTIONS]"
 }
 die() {
     echo "error: $@" >&2
@@ -59,9 +61,23 @@ sq() {
     git rev-parse --sq-quote "$@"
 }
 
+evalit() {
+    e=0
+    eval "$1" || e=$?
+    if test "$e" -ne 0 ; then
+        if test -n "$fail" ; then
+            exit "$e"
+        else
+            exit="$e"
+        fi
+    fi
+    return 0
+}
+
 main() {
     dryrun=""
     verbose=""
+    fail=""
     debug=""
     branch=""
     if ! type "git" 1>/dev/null 2>&1 ; then
@@ -71,7 +87,7 @@ main() {
         die "Not a git repository (or any of the parent directories)"
     fi
 
-    while getopts ":hvnb:d" opt ; do
+    while getopts ":hvenb:d" opt ; do
         case "$opt" in
         h)
             usage
@@ -79,6 +95,9 @@ main() {
             ;;
         v)
             verbose="true"
+            ;;
+        e)
+            fail="true"
             ;;
         n)
             dryrun="true"
@@ -115,13 +134,16 @@ main() {
     done
 
     eval set -- "${remotes:-}"
+
+    exit=0
     for rem in "$@" ; do
         if test -z "${branch:-}" ; then
-            eval "doit git push${git_opts:-} $(sq "$rem")"
+            evalit "doit git push${git_opts:-} $(sq "$rem")"
         else
-            eval "doit git push${git_opts:-} $(sq "$rem") $(sq "$branch")"
+            evalit "doit git push${git_opts:-} $(sq "$rem") $(sq "$branch")"
         fi
     done
+    exit "$exit"
 }
 
 trap "echo \"caught SIGINT\" ; exit 1 ;" INT
